from snakemake.utils import min_version
min_version("8.0")

import os
from glob import glob
import yaml

configfile: "../config/config.yaml"
SAMPLES, = glob_wildcards(os.path.join(config["reads"],config["fastq_names_1"]))

dir = dict()

# system directories
dir["base"] = os.path.join(workflow.basedir, "..")
dir["env"] = os.path.join(workflow.basedir, "envs")
dir["scripts"] = os.path.join(workflow.basedir, "..", "scripts")
dir["db"] = os.path.join(workflow.basedir, "databases")

# output directories
dir["out"] = config["output"]

# misc output directories
dir["temp"] = os.path.join(dir["out"], "temp")
dir["results"] = os.path.join(dir["out"], "results")
dir["logs"] = os.path.join(dir["out"], "logs")
dir["reports"] = os.path.join(dir["out"], "reports")
dir["bench"] = os.path.join(dir["out"], "benchmarks")
dir["output"] = os.path.join(dir["results"], "output")
dir["stats"] = os.path.join(dir["results"], "stats")

include: "rules/check_fastq.smk"
include: "rules/preprocessing.smk"

rule all:
    input:
        #expand(os.path.join(dir["output"],"{sample}_R2.fastq.gz"), sample = SAMPLES),
        os.path.join(dir["stats"], "initial_summary.txt"),
        os.path.join(dir["stats"], "multiqc_report.html"),
        expand(os.path.join(dir["output"], "fastp", "{sample}_R2_trimmed.fastq.gz"), sample = SAMPLES),
        #expand(os.path.join(dir["stats"], "rm_vector_contamination", "{sample}_rm_vc.stats"), sample = SAMPLES)
        expand(os.path.join(dir["output"], "bbmerge", "{sample}_merged.fastq.gz"), sample = SAMPLES),
    default_target: True
