# slurm resource configuration
executor: slurm

# Resources to use if not otherwise specified    
default-resources:
  - mem_mb=16000
  - runtime=1440
  - cores=24
  - slurm_account=sahlab

jobs: 40
latency-wait: 60 
use-conda: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy

set-resources:
    map_shreds:
        mem: 64G
    pB_step_1:
        mem: 24G
    pB_step_2:
        mem: 24G
    pB_step_3:
        mem: 24G
    pB_step_4:
        mem: 24G
    mask_host:
        mem: 64G
    index_host:
        mem: 64G
    host_removal:
        mem: 64G 
    megahit_coassembly:
        mem: 300G
        runtime: 4000
    megahit_individual_assembly:
        mem: 64G
        runtime: 1440
    flye_merge_assemblies:
        mem: 128G
        runtime: 2880
    map_reads_to_contigs:
        mem: 64G
    generate_per_sample_coverage:
        mem: 100G
