reads:
output: "out"
log:
fastq_names_1: "{sample}_R1.fastq.gz"
fastq_names_2: "{sample}_R2.fastq.gz"


viral_db: "/ref/sahlab/data/virus_genome_db/sequences_20241205_4728509.fasta"
host_ref: "/ref/sahlab/data/human_T2T/data/GCF_009914755.1/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna"
host_ref_masked: "/ref/sahlab/data/human_T2T/masked.fa"  

qc:
    fastp:
        --qualified_quality_phred=15
        --length_required=90
        --cut_tail
        --cut_tail_window_size=25
        --cut_tail_mean_quality=15
        --trim_poly_g
        --trim_poly_x
        --detect_adapter_for_pe
    bbduk:
        s1:
          ktrim=l
          k=8
          rcomp=f
          ordered=t
          ow=t
        s2:
          ktrim=r
          k=8
          rcomp=f
          ordered=t
          ow=t
        s3_and_4:
          ktrim=r
          k=19
          rcomp=f
          ordered=t
          ow=t
        rm_vc:
          k=31
          hammingdistance=1
          ordered=t
          ow=t
        rm_lq:
          ordered=t
          qtrim=r
          maxns=2
          entropy=0.5
          entropywindow=25
          trimq=15
          minlength=90
    bbmerge:
        minoverlap=20
    
