reads:
output: "out"
log:
fastq_names_1: "{sample}_R1.fastq.gz"
fastq_names_2: "{sample}_R2.fastq.gz"

trimmers:
  - fastp
  - roundAB

qc:
    compression:
         1
    bbduk:
        rm_5p:
          k=16
          hdist=1
          mink=11
          ktrim=l
          restrictleft=20
          removeifeitherbad=f
          trimpolya=10
          ordered=t
          rcomp=f
          ow=t
        rm_3rt:
          k=16
          hdist=1
          mink=11
          ktrim=r
          removeifeitherbad=f
          ordered=t
          rcomp=f
          ow=t
        neb:
          k=16
          hdist=1
          mink=10
          ktrim=r
          removeifeitherbad=f
          ordered=t
          rcomp=t
          ow=t
        rm_afp:
          k=16
          hdist=1
          removeifeitherbad=f
          ordered=t
          rcomp=t
          ow=t
        rm_vc:
          k=31
          hammingdistance=1
          ordered=t
          ow=t
        rm_lq:
          ordered=t
          qtrim=r
          maxns=2
          entropy=0.5
          entropywindow=25
          trimq=15
          minlength=90
